#!/usr/bin/env python


'''
Usage:
    mkapp --config <configfile> --project-name <name> [--force]
    mkapp --config <configfile> --load-schema <gql_schemafile>

Options:
    -f --force      Force overwrite of generated graphql schema file
'''

import os, sys
from collections import namedtuple
import docopt
import yaml
import jinja2
from snap import common
from griputil import create_gql_schema, generate_app_source, generate_resolver_source, generate_handler_source
from templates import MAIN_APP_TEMPLATE


def main(args):
    #print(common.jsonpretty(args))

    configfile_name = args['<configfile>']
    yaml_config = common.read_config_file(configfile_name)
    project_home = common.load_config_var(yaml_config['globals']['project_home'])
    schema_filename = args['<gql_schemafile>']

    # add the project home to our PYTHONPATH
    sys.path.append(os.path.join(os.getcwd(), project_home))

    if args['--project-name']:
        schema = create_gql_schema(yaml_config)
        # TODO: account for file paths relative to current dir

        project_name = args['<name>']
        schema_filename = f'{project_name}.graphql'
        schema_outfile = os.path.join(project_home,
                                      schema_filename)

        if os.path.isfile(schema_outfile):
            if args['--force'] == False:
                print(f'schema file {schema_outfile} already exists. Use -f to force overwrite.')
                return
        
        with open(schema_outfile, 'w') as f:
            f.write(schema)
        
    elif args['--load-schema']:
        schema_infile = os.path.join(project_home,
                                     schema_filename)

        with open(schema_infile) as f:
            schema_data = f.read()

    resolver_module = yaml_config['globals']['resolver_module']
    handler_module = yaml_config['globals']['handler_module']
    service_module = yaml_config['globals']['service_module']
    
    resolver_filename = f'{resolver_module}.py'
    handler_filename = f'{handler_module}.py'
    service_filename = f'{service_module}.py'

    resolver_filepath = os.path.join(project_home, resolver_filename)
    handler_filepath = os.path.join(project_home, handler_filename)

    if os.path.isfile(handler_filepath):
        if args['--force'] == False:
            print(f'schema file {schema_outfile} already exists. Use -f to force overwrite.')
            return

        with open(handler_filepath, 'w') as f:
            f.write(generate_handler_source(yaml_config))

    if not os.path.isfile(resolver_filepath):
        if args['--force'] == False:
            print(f'schema file {schema_outfile} already exists. Use -f to force overwrite.')
            return
        
        with open(resolver_filepath, 'w') as f:
            f.write(generate_resolver_source(yaml_config))

    print(generate_app_source(schema_filename, yaml_config))


if __name__ == '__main__':
    args = docopt.docopt(__doc__)
    main(args)