# YAML init file for Grip GraphQL framework
#

globals:
    project_home: $GRIP_HOME
    service_module: test_services
    resolver_module: test_resolvers
    handler_module: test_handlers
    debug_mode: True
    port: 5050
    logfile: grip.log
    

service_objects:
    test:
        class: TestService
        init_params:


type_defs:
    Greeting:
        id: Int!
        word: String!
        person: String!

    Building:
        id: ID!
        buildYear: String!
        residents: [Resident]

    Resident:
        id: ID!
        name: String!
        age: Int!
        family: [Resident]
        building: Building


mutation_defs:
    mutx:
        inputs:
        output: String!

    m2:
        inputs:
        output: String!

query_defs:
    hello:
        output: String!

    helloperson: 
        output: Greeting!

    sum:
        inputs:
            - a: Int!
            - b: Int!

        output: Int!

    reverse:
        inputs:
            - word: String!

        output: String!

    something:
        output: String!

entry_point:
    graphql_get:
        route: /graphql
        method: GET
        handler: handle_get
    






